apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: mysite
spec:
  host: mysite-test.apps-crc.testing
  port:
    targetPort: 8080
  to:
    kind: Service
    name: mysite
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect